import type { Metadata } from "next";
import { Inter } from "next/font/google";
import styles from './global.module.css'
import { ScrollProvider } from "./helper/scrollToContext";
import PageSelector from "./components/PageSelector";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Jenny's Websites",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
    <html lang="en">
      <body className={styles.body}>
        <ScrollProvider>
          {children}
        </ScrollProvider>
        </body>
    </html>
    </>
  );
}
